version: '3.3'
services:
  db-accept:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'insurance-accept'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'adminadminadmin'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'adminadminadmin'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db-accept:/var/lib/mysql
  db-prod:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'insurance-prod'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'adminadminadmin'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'adminadminadmin'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3307 on the container
      - '3307'
      # Where our data will be persisted
    volumes:
      - my-db-prod:/var/lib/mysql
# Names our volume
volumes:
  my-db-accept:
  my-db-prod: